import Navbar from "@/app/page-components/nav-header/page";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
  title: "Coursify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head>
        <style>
          @import url("https://fonts.googleapis.com/css2?family=Send+Flowers&display=swap");
          @import url("https://fonts.googleapis.com/css2?family=DynaPuff:wght@400..700&display=swap");
        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <main className="w-full">
          <TooltipProvider>{children}</TooltipProvider>
        </main>
      </body>
    </html>
  );
}
